### ISSUE TITLE
Technology suggest

### ISSUE THREAD

**Issue by chen01234567** [memoryfraction/LLSDA-Lightning-Location-System-Data-Analyzer#3]
首先非常感谢作者的无私奉献，但希望能提供技术路线，让发动机转得更远

**Comment by memoryfraction** [comment]
感谢使用 @chen01234567

**Comment by memoryfraction** [comment]
> 首先非常感谢作者的无私奉献，但希望能提供技术路线，让发动机转得更远
参考文件可以在https://github.com/memoryfraction/LLSDA-Lightning-Location-System-Data-Analyzer/tree/master/Documents或者中国知网下载
